version: '3'

services:
  postgres:
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
    volumes:
      - ./database:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  mqtt:
    image: toke/mosquitto
    ports:
      - '1883:1883'
    depends_on: [ postgres ]      

  producer:
    build: Producer/.    
    depends_on: [ postgres, mqtt ]

  consumer:
    build: Consumer/.
    environment:
      - HOST=postgres
      - USER=user    
      - PASSWORD=example
      - DATABASE=test
      - PORT=5432
    depends_on: [ postgres, mqtt, producer ]